name: react-native-build-packages
on:
#  # run on push
#  push:
#    branches:
#      - main
  # allow manual run
  workflow_dispatch:
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install npm dependencies
      run: npm install

  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Install npm dependencies
      run: npm install
    - name: Build Android Release
      run: cd android && ./gradlew assembleRelease
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: android-release
        path: android/app/build/outputs/apk/release/

