# Warning, do not check out untrusted code with
# the pull_request_target event.
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
permissions:
  pull-requests: write
name: Labeling
jobs:
  labeler:
    name: Apply labels
    runs-on: ubuntu-latest
    steps:
      - name: Set labels based on conventional commits types
        uses: bcoe/conventional-release-labels@v1
        with:
          type_labels: |
            {
              "breaking": "cc-breaking",
              "feat": "cc-feat",
              "fix": "cc-fix",
              "build": "cc-build",
              "ci": "cc-ci",
              "docs": "cc-docs",
              "perf": "cc-perf",
              "refactor": "cc-refactor",
              "style": "cc-style",
              "test": "cc-test" 
            }
  not-hold: 
    name: Ensure PR not in hold
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: mheap/github-action-required-labels@v3
        with:
          mode: exactly
          count: 0
          labels: "pr-hold"
